apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cnf
spec:
  version: {{ .TagName }}
  homepage: https://github.com/hedgieinsocks/kubectl-cnf
  shortDescription: Switch between k8s configs within a terminal tab
  description: |
    The plugin facilitates convenient kubeconfig selection
    It optionally launches a subshell with the chosen KUBECONFIG
    This way you can multitask by dedicating each cluster its own terminal tab
  caveats: |
    Dependencies: fzf, bat
    Prepare: create ~/.kube/configs directory and put there your kubeconfigs
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - linux
        - darwin
    {{ addURIAndSha "https://github.com/hedgieinsocks/kubectl-cnf/archive/refs/tags/{{ .TagName }}.tar.gz" .TagName }}
    files:
    - from: kubectl-cnf-*/kubectl-cnf
      to: .
    - from: kubectl-cnf-*/LICENSE
      to: .
    bin: "./kubectl-cnf"
